USERS_LIST = [{:first_name => "Greg", :last_name => "Henry", :age => 34},
              {:first_name => "Mary", :last_name => "Beth", :age => 45},
              {:first_name => "Gina", :last_name => "Sue", :age => 66},
              {:first_name => "David", :last_name => "Illheim", :age => 12},
              {:first_name => "Ward", :last_name => "Deverson", :age => 24},
              {:first_name => "Miles", :last_name => "Guster", :age => 72},
              {:first_name => "Samael", :last_name => "Ouver", :age => 99},
              {:first_name => "Chuck", :last_name => "Testa", :age => 31},
              {:first_name => "Dwayne", :last_name => "Johnson", :age => 50},
              {:first_name => "Tooth", :last_name => "Fairy", :age => 83},]
